(cl:in-package #:huginn-user)

(defparameter *data* (make-database 'huginn.m.d:database t))

(progn
  (clear)

  (<- `(house ? ? ? ? ?))
  (<- `(= ?item ?item))
  (<- `(member ?item ,(li '(?item . ?rest))))
  (<- `(member ?item ,(li '(? . ?rest)))
      '(member ?item ?rest))
  (<- `(iright ?left ?right ,(li `(?left ?right . ?))))
  (<- `(iright ?left ?right ,(li `(? . ?rest)))
      `(iright ?left ?right ?rest))
  (<- `(nextto ?x ?y ?list)
      `(iright ?x ?y ?list))
  (<- `(nextto ?x ?y ?list)
      `(iright ?y ?x ?list))

  (<- `(zebra ?houses)
      `(= ?houses ,(li '((house norway ? ? ? ?) ? ? ? ?)))
      `(member (house england ? ? ? red) ?houses)
      `(member (house spain dog ? ? ?) ?houses)
      `(member (house ? ? ? coffe green) ?houses)
      `(member (house ukrain ? ? tea ?) ?houses)
      `(iright (house ? ? ? ? ivory)
               (house ? ? ? ? green)
               ?houses)
      `(member (house ? snails winston ? ?) ?houses)
      `(member (house ? ? kools ? yellow) ?houses)
      `(nextto (house ? ? chesterfield ? ?)
               (house ? fox ? ? ?)
               ?houses)
      `(nextto (house ? ? kools ? ?)
               (house ? horse ? ? ?)
               ?houses)
      `(member (house ? ? luckystrike orange-juice ?)
               ?houses)
      `(member (house japan ? parliments ? ?)
               ?houses)
      `(nextto (house norway ? ? ? ?)
               (house ? ? ? ? blue)
               ?houses))

  (defparameter *answer* (?- '(zebra ?houses)))
  (print (cl-ds:consume-front *answer*)))
