(cl:in-package #:huginn-user)

(defparameter *data* (make-database 'huginn.m.d:database t))

(defmacro house (nation pet smokes drinks house-color)
  ``(house ,',nation ,',pet ,',smokes ,',drinks ,',house-color))

(progn
  (clear)

  (<- `(house ?nation ?pet ?drinks ?house-color))
  (<- `(= ?item ?item))
  (<- `(iright ?left ?right ,(li `(?left ?right . ?rest))))
  (<- `(iright ?left ?right ,(li `(? . ?rest)))
      `(iright ?left ?right ?rest))
  (<- `(nextto ?x ?y ?houses)
      `(iright ?x ?y ?houses))
  (<- `(nextto ?x ?y ?houses)
      `(iright ?y ?x ?houses))

  (<- `(zebra ?houses)
      `(= ?houses ,(li `((house norway ? ? ? ?) . ?rest)))
      (house england ? ? ? red)
      (house spain dog ? ? ?)
      (house ? ? ? coffe green)
      (house ukrain ? ? tea ?)
      `(iright (house ? ? ? ? ivory)
               (house ? ? ? ? green)
               ?houses)
      (house ? snails winston ? ?)
      (house ? ? kools ? yellow)
      `(nextto (house ? ? chesterfield ? ?)
               (house ? fox ? ? ?)
               ?houses)
      `(nextto (house ? ? kools ? ?)
               (house ? horse ? ? ?)
               ?houses)
      (house ? ? luckystrike orange-juice ?)
      (house japan ? parliments ? ?)
      `(nextto (house norway ? ? ? ?)
               (house ? ? ? ? blue)
               ?houses))

  (defparameter *answer* (?- `(zebra ?houses)))
  (print (cl-ds:consume-front *answer*))

  )
